module.exports = {
  week: "SINCE 21 SEP 2026",
  regions: [
    {name:"Western Europe", codes:["be","fr","ie","lu","nl","gb"], countries:[
      {code:"be", name:"Belgium", events:[
        {name:"Hackathon: Learn with the AI Loop", loc:"Ottignies-Louvain-la-Neuve", date:"14-15 Oct", tags:["Artificial Intelligence (AI)","Developer Tools / DX"]},
        {name:"odoo Hackathon", loc:"Grand-Rosière", date:"20-22 Nov", tags:[]},
      ]},
      {code:"fr", name:"France", events:[
        {name:"Université de Lille Hackathon 2026", loc:"Lille", date:"19 Oct-16 Nov", tags:["Sustainability","Energy Systems","Smart Cities","Artificial Intelligence (AI)","Social Impact"]},
      ]},
      {code:"ie", name:"Ireland", events:[
        {name:"hackucd", loc:"Dublin", date:"1-31 Oct", tags:[]},
        {name:"Notion 🖤's Dublin × Dublin AI Week: Student Hackathon 2026", loc:"Dublin", date:"9 Oct", tags:["Artificial Intelligence (AI)","Social Impact"]},
      ]},
      {code:"lu", name:"Luxembourg", events:[
        {name:"STATEC Hackathon 2026 (GovTech Lab)", loc:"Luxembourg", date:"14-16 Oct", tags:["Data Science & Analytics","GovTech / Public Sector","FinTech","Open Source","Social Impact"]},
        {name:"OdooHack Night: Merge or Die", loc:"Koerich", date:"12-13 Nov", tags:["Developer Tools / DX","Open Source"]},
      ]},
      {code:"nl", name:"Netherlands", events:[
        {name:"UvA AI Chat Hackathon", loc:"Amsterdam", date:"1 Oct", tags:["Artificial Intelligence (AI)","EdTech / Education Technology"]},
        {name:"#UTRECHT (Hack Your Utrecht)", loc:"Utrecht", date:"3 Oct", tags:["Cybersecurity"]},
        {name:"Hack Your First Web App | Guided TryHackMe CTF", loc:"Maastricht", date:"7 Oct", tags:["Cybersecurity","Gaming & Game Development"]},
        {name:"Hackathon Dutch Laravel Foundation", loc:"Leiden", date:"29 Oct", tags:["Developer Tools / DX","Open Source"]},
        {name:"Mage-OS Pre-MMNL Hackathon", loc:"Amsterdam", date:"4 Nov", tags:[]},
        {name:"Competence Lab Hackathon - Eindhoven | Global Entrepreneurship Week", loc:"Eindhoven", date:"17 Nov", tags:["Social Impact","Sustainability","Open Source"]},
      ]},
      {code:"gb", name:"United Kingdom", events:[
        {name:"Cyber Heist - Unleash Your Inner Hacker", loc:"Glasgow", date:"29 Sep", tags:["Cybersecurity","Social Impact"]},
        {name:"SCA Scratch Hackathon", loc:"Birmingham", date:"30 Sep", tags:[]},
        {name:"AlphaBeta Hackathon", loc:"London", date:"1 Oct", tags:[]},
        {name:"Dealroom API Hackathon", loc:"London", date:"1 Oct", tags:["Artificial Intelligence (AI)","Data Science & Analytics","API & Platform Engineering","FinTech"]},
        {name:"AdaHack", loc:"Edinburgh", date:"3 Oct", tags:[]},
        {name:"Back To Uni Canva Pitching Competition", loc:"London", date:"3 Oct", price:"£150", tags:["FinTech","Social Impact","EdTech / Education Technology"]},
        {name:"Ctrl+Space Hackathon - London", loc:"London", date:"3-8 Oct", tags:["AR / VR / XR","Developer Tools / DX"]},
        {name:"EAT_HACK - The world's first AI & eating hackathon", loc:"London", date:"3 Oct", price:"£1,000", tags:["Artificial Intelligence (AI)","Retail & E-Commerce","Data Science & Analytics"]},
        {name:"London AI x Science Hackathon", loc:"London", date:"3-4 Oct", tags:["Artificial Intelligence (AI)","Data Science & Analytics","Life Sciences & Biotechnology"]},
        {name:"RGU CADathon", loc:"Aberdeen", date:"3 Oct", tags:["Gaming & Game Development","Developer Tools / DX"]},
        {name:"AI Hackathon. Build an AI Tool in 6 Hours", loc:"Taunton", date:"8 Oct", tags:["Artificial Intelligence (AI)","Social Impact","HRTech"]},
        {name:"Marketing Camp: Hackathon", loc:"Abingdon", date:"8 Oct", tags:[]},
        {name:"Girls Hack Hard", loc:"London", date:"10-11 Oct", perks:["✈️ Travel"], tags:["Hardware & Embedded Systems","Women in Tech / Diversity"]},
        {name:"Buildathon with MongoDB, Vercel & Tavily", loc:"London", date:"14 Oct", tags:["Developer Tools / DX","Artificial Intelligence (AI)","FinTech"]},
        {name:"App After Dark: Mobile App Hackathon", loc:"London", date:"15 Oct", tags:["Artificial Intelligence (AI)","Gaming & Game Development","Developer Tools / DX"]},
        {name:"Investing in Thriving Communities at SustainableFinance Live", loc:"London", date:"16-27 Oct", tags:["Artificial Intelligence (AI)","Blockchain","Sustainability","FinTech","Social Impact"]},
        {name:"Chat Hackers - Hack Day", loc:"London", date:"17 Oct", tags:["Developer Tools / DX","Open Source","Social Impact"]},
        {name:"Physical AI Hack", loc:"London", date:"17 Oct", tags:["Artificial Intelligence (AI)","Robotics & Autonomous Systems","Internet of Things (IoT)","Industry 4.0 / Smart Manufacturing"]},
        {name:"FinOps Hackathon", loc:"London", date:"20 Oct", tags:["Artificial Intelligence (AI)","FinTech"]},
        {name:"Moonfire • Build Night Hackathon", loc:"London", date:"22 Oct", tags:["Artificial Intelligence (AI)"]},
        {name:"Canva Gen©️ - Student Hackathon London 🚀", loc:"London", date:"24 Oct", tags:["HCI / UX Innovation","Social Impact"]},
        {name:"HackNotts '26", loc:"Nottingham", date:"24-25 Oct", tags:["Developer Tools / DX","Open Source","Social Impact","Gaming & Game Development"]},
        {name:"Lovable x EF x WWB Hackathon", loc:"London", date:"24 Oct", tags:["Artificial Intelligence (AI)","Social Impact","Women in Tech / Diversity"]},
        {name:"OxHack", loc:"Oxford", date:"24-25 Oct", tags:["Artificial Intelligence (AI)"]},
        {name:"DEV HACK", loc:"Norwich", date:"28 Oct", tags:["Social Impact","Sustainability","CleanTech","Open Source"]},
        {name:"Hackathon Explore", loc:"London", date:"31 Oct", price:"£5,000", tags:["Social Impact","Open Source"]},
        {name:"Future Makers with Lloyds Banking Group", loc:"Dundee", date:"4-5 Nov", tags:["Social Impact","Women in Tech / Diversity","Artificial Intelligence (AI)","Gaming & Game Development","Developer Tools / DX"]},
        {name:"GreatUniHack 2026", loc:"Manchester", date:"7-8 Nov", price:"£70,000", tags:["Artificial Intelligence (AI)","API & Platform Engineering","Sustainability","FinTech","Social Impact"]},
        {name:"Hack the Gap", loc:"Bristol", date:"12 Nov", tags:["Artificial Intelligence (AI)","Data Science & Analytics","Social Impact","Women in Tech / Diversity"]},
        {name:"Hack for Impact: Sheffield", loc:"Sheffield", date:"13 Nov", tags:["Artificial Intelligence (AI)","Open Source","Developer Tools / DX","Social Impact"]},
        {name:"The St Andrews Hackathon", loc:"St Andrews", date:"15 Nov", tags:["Artificial Intelligence (AI)","Developer Tools / DX"]},
        {name:"RSE Hackathon 2026 at University of Glasgow", loc:"Glasgow", date:"26-27 Nov", tags:["Open Source","Developer Tools / DX","Reproducible Research"]},
        {name:"Rule Roulette - Game Jam", loc:"Edinburgh", date:"5 Dec", tags:["Gaming & Game Development"]},
      ]},
    ]},
  ],
  extraFlags: { lu: "flags/lu.svg" },
};
